// ==========================================
// PROYECTO ZERO
// Patrones de batería
// ==========================================

// Cada lista representa un compás de 8 pasos:
//
// 1   &   2   &   3   &   4   &
// 0   1   2   3   4   5   6   7

~kickPattern = [
    1, 0, 0, 0,
    1, 0, 0, 0
];

~snarePattern = [
    0, 0, 1, 0,
    0, 0, 1, 0
];

~hihatPattern = [
    0, 1, 0, 1,
    0, 1, 0, 1
];

"Patrones de batería cargados.".postln;